[package]
name = "fstrings"
version = "0.0.1"
authors = ["Daniel Henry-Mantilla <daniel.henry.mantilla@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro = { version = "0.0.1", package = "fstrings-proc-macro", path = "src/proc_macro" }
# proc-macro-hack = "0.5.8"

[features]
verbose-expansions = ["proc-macro/verbose-expansions", ]
